name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: './repo'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: run composite action
      uses: tbal999/actionapp@4
      with:
        args: './repo'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
