name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: run composite action
      uses: tbal999/actionapp@5
      with:
        one: './'
        two: ${{ secrets.SECRET_TOKEN }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
