name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: run composite action
      uses: tbal999/actionapp@v15      
      with:
        path: './'
        key: 'Thisisakey'
        space: 'ExampleSpace'
