name: testing out action

#TODO: create composite or docker action for puml job (row 27-39)

on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  puml:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Branch details
        shell: bash
        run: |
             if [ -z "${GITHUB_HEAD_REF}" ]
             then
              echo NOT pull request, branch = $(echo ${GITHUB_REF#refs/heads/})
              echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
             else
              echo pull request, branch = $(echo ${GITHUB_HEAD_REF})
              echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
             fi
        id: extract_branch          
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}
          path: './mainrepo'
          fetch-depth: 0
      - name: Markdown Action
        uses: tbal999/markdown-to-confluence@node@n1
        with:
          ref: ${{ env.BRANCH_NAME }}
          path: './'
          INPUT_CONFLUENCE_API_KEY: ""
          INPUT_CONFLUENCE_SPACE: "XM"
          INPUT_CONFLUENCE_USERNAME: "tom@xiatech.co.uk"
          PROJECT_PATH: "./mainrepo"
          fetch-depth: 0
