name: Generate plantuml files (.puml) & png diagram

#TODO: create composite or docker action for puml job (row 27-39)

on:
  push:
    branches:
      - '*'
      #- master
      #- main
  pull_request:
jobs:
  puml:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: |
             echo "##[set-output name=branch;]$(echo ${GITHUB_BASE_REF})"
             echo ${{ steps.extract_branch.outputs.branch }}
        id: extract_branch
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: './mainrepo'
          ref: ${{ steps.extract_branch.outputs.branch }}
          fetch-depth: 0
      - name: checkout plantuml
        uses: tbal999/go-plantuml-action@1
        with: 
          args: -v -tpng ./mainrepo
          path: './plantuml'
      - name: create puml file
        run: |
            cd ./plantuml
            if [ -f "../mainrepo/graph.puml" ] ; then
              rm "../mainrepo/graph.puml"
            fi
            if [ -f "../mainrepo/graph.png" ] ; then
              rm "../mainrepo/graph.png"
            fi
            cp graph.puml ../mainrepo
      - name: generate puml png diagram
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng ./mainrepo/graph.puml
      - name: pull & push
        run: |
            cd  ./mainrepo
            git config user.name github-actions
            git config user.email github-actions@github.com
            git pull
            git add graph.png
            git add graph.puml
            git diff-index --quiet HEAD || git commit -m "generated puml & png image"
            git push

